### ISSUE TITLE
ruchy: "freshly created" GK message is very confusing

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#423]
- New UI
- Try to log a GK without existing logs
- Check icons on the right

![image](https://user-images.githubusercontent.com/918446/60197321-72544e00-983f-11e9-89ef-ff023fe9b420.png)

I do not understand what "plus" icon means there, also there is no tooltip for it.
Also there is "last log" title, but nothing after colon, probably should be removed.

**Comment by kumy** [comment]
I know, this part is still bugged ;)

**Comment by kumy** [comment]
Should be fixed now

**Comment by okainov** [comment]
Hmm... I wouldn't say so...

![image](https://user-images.githubusercontent.com/918446/60216304-f6bbc680-9869-11e9-9783-e60a0614a68b.png)


And the icon is still not clear

**Comment by kumy** [comment]
That s the iconology of the current website.

My goal is the provide a new base for fresh contributions. Such little details are welcome to those kind of contribution. :)

**Comment by kumy** [comment]
@okainov would you provide a different icon?

**Comment by okainov** [comment]
I would just add a tooltip first :) Design is not my best side =)

**Comment by kumy** [comment]
(Same here about design). I'm quite surprized about the missing tooltip, as I've checked it on another GK that had a different lastlogtype that "created" and it was there. Is this missimg tt only for the "new" logtype?

**Comment by kumy** [comment]
Tooltip are present at lest for logtype "dipped" and "seen"
![Screenshot from 2019-06-27 20-03-41](https://user-images.githubusercontent.com/176794/60289461-bebe8d00-9916-11e9-8d75-a8a53a19140e.png)

**Comment by kumy** [comment]
Confirmed, "freshly created" logtype has no tooltip.

**Comment by kumy** [comment]
@okainov hope that's fine now.

**Comment by okainov** [comment]
I would propose (maybe it was not clear from the initial description, I don't know. But that's what I meant from the very beginning actually) to just remove this completely or replace to some proper text like "no logs". Because it's really confusing - there are no logs, why site shows to me "last log one week ago"?

![image](https://user-images.githubusercontent.com/918446/60321298-ada86700-997c-11e9-9962-53534d76e552.png)

**Comment by kumy** [comment]
@okainov 
![Screenshot from 2019-06-28 19-11-09](https://user-images.githubusercontent.com/176794/60359284-ee35ce00-99d8-11e9-9c42-7082345000e2.png)
